//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APICatalogo.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APICatalogo.Exceptions.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição do produto deve ser informada..
        /// </summary>
        public static string DESCRIPTION_EMPTY {
            get {
                return ResourceManager.GetString("DESCRIPTION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da categoria deve ser informado..
        /// </summary>
        public static string NAME_CATEGORY_EMPTY {
            get {
                return ResourceManager.GetString("NAME_CATEGORY_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do produto deve ser informado..
        /// </summary>
        public static string NAME_PRODUCT_EMPTY {
            get {
                return ResourceManager.GetString("NAME_PRODUCT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O preço do produto deve ser informado..
        /// </summary>
        public static string PRICE_EMPTY {
            get {
                return ResourceManager.GetString("PRICE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O preço do produto deve ser maior que zero..
        /// </summary>
        public static string PRICE_MIN {
            get {
                return ResourceManager.GetString("PRICE_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O estoque deve ser informado..
        /// </summary>
        public static string STOCK_EMPTY {
            get {
                return ResourceManager.GetString("STOCK_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor de estoque do produto deve ser maior que zero..
        /// </summary>
        public static string STOCK_MIN {
            get {
                return ResourceManager.GetString("STOCK_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A URL da Imagem da categoria deve ser informada..
        /// </summary>
        public static string URL_IMAGE_CATEGORY_EMPTY {
            get {
                return ResourceManager.GetString("URL_IMAGE_CATEGORY_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A URL da Imagem da categoria  deve ter no máximo 255 caracteres..
        /// </summary>
        public static string URL_IMAGE_CATEGORY_MAX {
            get {
                return ResourceManager.GetString("URL_IMAGE_CATEGORY_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A URL da Imagem do produto deve ser informada..
        /// </summary>
        public static string URL_IMAGE_PRODUCT_EMPTY {
            get {
                return ResourceManager.GetString("URL_IMAGE_PRODUCT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A URL da Imagem do produto deve ter no máximo 255 caracteres..
        /// </summary>
        public static string URL_IMAGE_PRODUCT_MAX {
            get {
                return ResourceManager.GetString("URL_IMAGE_PRODUCT_MAX", resourceCulture);
            }
        }
    }
}
